### ISSUE TITLE
Add Option to Only Allow Player Scavs to Loot

### ISSUE THREAD

**Issue by dwesterwick** [Skwizzy/SPT-LootingBots#101]
Please add an additional option to only allow player Scavs to loot. When implemented, this means the existing "Scav" checkbox will allow all non-player Scavs to loot.

The code I'm using to check which Scavs are player Scavs is: 
```// Pattern: xxx (xxx)
string pattern = "\\w+.[(]\\w+[)]";
Regex regex = new Regex(pattern);
if (regex.Matches(botOwner.Profile.Nickname).Count > 0)
{
    return BotType.PScav;
}

**Comment by dwesterwick** [comment]
@Skwizzy I messed up the Regex pattern because I forgot that bot names can have special characters in them. This should fix it: `string pattern = ".+[(].+[)]";`.

**Comment by Skwizzy** [comment]
Changes can be found here: 179f692

**Comment by dwesterwick** [comment]
Thank you!
