### ISSUE TITLE
SudisCain - AKI 3.5.0  Raid stuck at "Ready"

### ISSUE THREAD

**Issue by Skwizzy** [Skwizzy/SPT-LootingBots#18]
SudisCain reports: 

This mod seems cool but I can't seem to get it to work. Everytime I try to join any raid, it just gets stuck on "READY". I check the logs and it does not go through its usual checks.

Mods I use:
- Fin's AI rework
- ServerValueModifier
- Amanda.Graphics
- Kokrakon; Take a break

The log is too long to put but I'll show you a snippit of it. It's repititive and will just go through all the AI list.

[Client Request] /client/raid/configuration

[Client Request] /player/health/sync

[Client Request] /singleplayer/settings/bot/difficulty/core/core

[Client Request] /singleplayer/settings/bot/difficulty/sptBear/easy

[Client Request] /singleplayer/settings/bot/difficulty/sptBear/normal

[Client Request] /singleplayer/settings/bot/difficulty/sptBear/hard

[Client Request] /singleplayer/settings/bot/difficulty/sptBear/impossible

[Client Request] /singleplayer/settings/bot/difficulty/marksman/easy

[Client Request] /singleplayer/settings/bot/difficulty/marksman/normal

[Client Request] /singleplayer/settings/bot/difficulty/marksman/hard

[Client Request] /singleplayer/settings/bot/difficulty/marksman/impossible

**Comment by Deslicia** [comment]
My bad... I was using my backup directory... All is OK !
Thank you for correction, thank you very much for the mode, and sorry for my error.

**Comment by Skwizzy** [comment]
3.5.0 compatible version now available https://github.com/Skwizzy/SPT-LootingBots/releases/tag/v1.0.1-aki-3.5.0
