### ISSUE TITLE
Object detection distances settings for loot for each type looting (enhancement)

### ISSUE THREAD

**Issue by MrFlashMode** [Skwizzy/SPT-LootingBots#65]
Ability to set the detection range of the object for the loot for each type from the looting

For example:
15 meters for detecting a body that can be looted

30 meters for detecting a loose loot that can be picked up

60 meters for detecting containers with loot

It would be extremely nice to have such a settings, it would be possible to allow the Followers to loot the corpses of those killed, but at the same time, so they do not run away from his boss

**Comment by Skwizzy** [comment]
This is a good suggestion, I'll add this in for next release
