### ISSUE TITLE
Bloodhounds (arenaFightersEvent) bot type is missing

### ISSUE THREAD

**Issue by MrFlashMode** [Skwizzy/SPT-LootingBots#68]
Looking through the 3.5.8 branch source code, I didn't notice any mention of the Bloodhound faction (arenaFightersEvent)

It seems like a small issue

**Comment by Skwizzy** [comment]
Ah totally forgot to add this in 3.5.8, I'll add it as a separate bot type in the mod settings. Thanks for opening the issue :)

**Comment by Skwizzy** [comment]
Should be fixed by  a87e8ad
