### ISSUE TITLE
SAIN Mod

### ISSUE THREAD

**Issue by Elite911** [Skwizzy/SPT-LootingBots#79]
Hello,

Is this mod compatible with SAIN Solarint's AI Modifications mod or is there conflicts?

https://hub.sp-tarkov.com/files/file/1062-sain-2-0-solarint-s-ai-modifications-full-ai-combat-system-replacement/

**Comment by Skwizzy** [comment]
Yes this mod is compatible with SAIN, helps diversify bot behavior even more
